build:	
	gcc ./ASL.c -o ASL.out -lSDL 
	# -Wall -Wextra # Thanks to Fififox and ninzine from #ludumdare for the help with the SDL libs and the waring options (-Wall -Wextra) :D

build onNT:
	gcc ./ASL.c -o ASL.out -lmingw32 -lSDLmain -lSDL
	# Install SDL with minGW on windows as per: http://stackoverflow.com/questions/8307091/setting-up-sdl-in-mingw